singleuser:
  serviceAccountName: jovyan
  defaultUrl: "/lab"
  cpu:
    limit: 2
    guarantee: 1
  memory:
    limit: 8G
    guarantee: 7G
  image:
    name: uwhackweek/snowex
    tag: latest

hub:
  config:
    JupyterHub:
      authenticator_class: github
    Authenticator:
      auto_login: true
      admin_users:
        - scottyhq
        - lsetiawan

proxy:
  https:
    enabled: true
    hosts:
      - snowex.hackweek.io
    letsencrypt:
      contactEmail: scottyh@uw.edu
