name: Helm
on:
  pull_request:
    paths:
      - 'hub/**.yaml'
      - '.github/workflows/Helm.yml'
  push:
    branches:
      - 'main'
    paths:
      - 'hub/**.yaml'
      - '.github/workflows/Helm.yml'

jobs:
  helm:
    name: Helm
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        role-to-assume: github-actions-role
        role-duration-seconds: 900

    # NOTE: hardcoded cluster name, should make an env variable and match 'release' and 'namespace'
    - name: Connect to EKS Cluster
      run: |
        aws eks --region us-west-2 update-kubeconfig --name snowex-hackweek

    - name: Setup Helm
      run: |
        helm version
        helm repo add stable https://charts.helm.sh/stable
        helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
        helm plugin install https://github.com/jkroepke/helm-secrets --version v3.5.0
        helm repo update
        helm list -A

    - name: Sops Binary Installer
      uses: mdgreenwald/mozilla-sops-action@v1
      with:
        version: '3.6.1'

    # Only upgrade if we've committed to main branch
    - name: Helm upgrade
      if: github.ref == 'refs/heads/main'
      env:
        SOPS_KMS_ARN: ${{ secrets.SOPS_KMS_ARN }}
        RELEASE: jhub
        NAMESPACE: jhub
      run: |
        helm upgrade --cleanup-on-fail \
          --install $RELEASE jupyterhub/jupyterhub \
          --namespace $NAMESPACE \
          --create-namespace \
          --version=0.11.1 \
          --values hub/config.yaml \
          --values secrets://hub/secrets.yaml
